### ISSUE TITLE
Various Ideas for the website

### ISSUE THREAD

**Issue by Angelazielinski** [thomasmarkiewicz/calma#1]
Hi...hopefully this will  be what you need...there is a lot going on in this site :)

So these are a few items that I've been thinking would be a good thing to have.  Now keep in mind I have NO idea if this is a lot of work, if it is...please let me know.  I really appreciate you doing all of this and although I know you said its no big deal, if it gets to be too much please let me know and let me know what the cost would be to get it to where it needs to be.

Most important for now...can you please change the picture of the XL Eggs, they are still wrong :)

1~ When you go to the website, can there be one page that has a map and lists all locations we service underneath?  If we need to add stores, is this something I can do or should I just message you?  

2~ When clicking on the item, I know the list of stores that its available at shows up but it would be nice if a picture of that product stayed up on top.  Also, I wanted to post the back of the labels for the products, where would be a good place to have that?  I assume you are making this more mobile friendly than desktop?  Because on a desktop, if you hover over something then you can maybe see more details, or if you just click on it I can have the labels show up then?  I'll try to find examples of other websites.  https://kalonasupernatural.com/product/organic-milk-cream/organic-whole-milk/  ~ this is a company we distribute for...they have a decent website.  Lots of information, not sure I need all of this for now.

3~ Write  " We Bring Amish Country Into Your Home" at the top of the front page in Caveat Font.  

I think that's all for now...oh, I'll email you the logo once I have it kind of more finalized.

**Comment by thomasmarkiewicz** [comment]
hey @Angelazielinski - you did it, congrats ;)
I broke out this issue into multiple smaller issues that we can address separately.
